export DENO_INSTALL="/Users/joeyvico/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
export LANG=en_US.UTF-8

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Path to your oh-my-zsh installation.
export ZSH="/Users/joeyvico/.oh-my-zsh"

ZSH_THEME="spaceship"
SPACESHIP_TIME_SHOW="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

plugins=(git colored-man-pages zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# User configuration
# export MANPATH="/usr/local/man:$MANPATH"

# clear
neofetch

alias vim="nvim"
alias neovim="nvim"
alias repos='echo "Listing repositories ..." && cd ~/repos && ls'
alias cat="bat"
alias editz="nvim ~/.zshrc"
alias editnv="nvim ~/.config/nvim/init.vim"
alias sourcez="source ~/.zshrc"

fpath=($fpath "/Users/joeyvico/.zfunctions")

  # Set Spaceship ZSH as a prompt
  autoload -U promptinit; promptinit
  prompt spaceship

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
